{
 "title": "SRE Capstone - E-commerce API",
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"ecommerce-api\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"ecommerce-api\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"ecommerce-api\"}[5m])) * 100",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"ecommerce-api\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Availability SLO 99%",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{job=\"ecommerce-api\",status_code=~\"5..\"}[30m])) / sum(rate(http_requests_total{job=\"ecommerce-api\"}[30m])))) * 100",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "max(0, (0.01 - (sum(rate(http_requests_total{job=\"ecommerce-api\",status_code=~\"5..\"}[30m])) / sum(rate(http_requests_total{job=\"ecommerce-api\"}[30m])))) / 0.01 * 100)",
     "legendFormat": "Budget %"
    }
   ]
  }
 ]
}